dist: trusty
group: beta
language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
before_install:
- if [ -d node_modules ] && [ x$(cat node_modules/.last-node-version 2>/dev/null) != x$(node -e 'console.log(process.version)') ]; then npm rebuild --update-binary && node -e 'console.log(process.version)' > node_modules/.last-node-version; fi
deploy:
  skip_cleanup: true
  provider: npm
  email: npm@collaborne.com
  api_key:
    secure: "qKAWed6o8c2jisNoEpk5f/TkZOOVOMtLOpByaHuTSo0K5Wuk1A8wr3BPDA6xgrdpNTufB42tugbG5V4h8SOSenst9NfR9VUFfQJkIFN3JjDhAZsJwE/0cFw69vcAQi6dGFmCdMAkkwx0AAJdKXQIUWFPE8Xh+ub/uopjY+uI+JPp8xCn5NYUlx9M/Bbgnk88lSvuuaKeWAUTDgvQvmuJDEmAQ6h6yP4VycVyk6ZJ7sn1WuLey6yICCLvZvpI/HQ5ZkYEop29QirlVgw/lG1cFixITNmanJZCm9OiyuN26R8aoTCftyym80Rom66uSlbnxvrIIkTyBzhjKu6OGoVTHXo3UKA+JGlYWvQbFhhnoDwIn1yEdKFPIwPj49IjHSGoJmKL/Z3A3F8vExgxh7cRimrhUQYjFLlFLh+SDhhnEPZs5YLPB+P+/enBSDFFqdNNB6dVjtBAbeJdapsd42ENU/rHSNsHWFoaSOcJ7Mp74IPHU5LsYLXs/NOfAz931piC3xS7eb2kO/ofG5Q8Wi4yIWP7TzFkgd09Q54+CtzLEY3CEPfH7ag+5qpmNjQ0FGJKysif4RgcUFihEDVSXjSmyOKgrnkd8RNrMU7DzGSDxD4NzHLuyaNNAEDRfI1Bi4PMgfehacB9ZQ1nZUITOwiZlQhwc7mlTdXSMGsTAWbhbHs="
  on:
    tags: true
    condition: $(node -e 'console.log("v" + require("./package.json").version)') = ${TRAVIS_TAG}
